### ISSUE TITLE
Simplify Nvidia dependencies

### ISSUE THREAD

**Issue by andyl** [elixir-nx/xla#101]
For a given version of EXLA, I find it difficult to know which combination of CUDA drivers, CUDA runtime and cuDNN are needed to make everything work.

Just posting an idea here: Could EXLA/XLA install these dependencies automatically?  Or emit a bash script to set things up properly?  Or include some sort of healthcheck task?

**Comment by polvalente** [comment]
Other than looking in the README for the https://github.com/elixir-nx/xla?tab=readme-ov-file#xla_target table, which does specify the expected versions, I believe automatically installing these would be too invasive.

As a personal anectode, _every time_ my Linux kernel updates, I have to tweak the NVIDIA driver installation -- and the easiest way is to reinstall the NVIDIA drivers and CUDA. If EXLA started tampering with that as well, it could become an unstable system.

I think we could, however, provide some sort of `mix xla.check_version --target cuda12` or something similar, where we validate the dependencies for each of the given lines, and emit a warning/fail the task when the validation fails.

**Comment by andyl** [comment]
Thanks @polvalente a `check_version` task would be great!  Would you like me to submit a PR for it?  If so, LMK if there are features you would like, or guidelines you would like me to follow.

**Comment by jonatanklosko** [comment]
I think portable checks would be problematic. For example, to find out cuDNN version, I'm not sure if there's a more reliable way than searching installed system packages, which is OS-specific. Perhaps we could look for certain files, but I'm pretty sure that's going to be too brittle.

Maybe we should make the EXLA->XLA navigation version aware. Currently the EXLA docs link to `https://github.com/elixir-nx/xla`, which is always main. We could instead link to `` `XLA` `` and then include the versions information in the `XLA` module docs. Or perhaps that's still too much and we should move all information to the EXLA docs altogether. @josevalim @polvalente thoughts?

**Comment by polvalente** [comment]
I like the idea of linking to XLA and having the version-aware info there!

**Comment by jonatanklosko** [comment]
I opened PRs with docs improvements, I'm going to close this.
