### ISSUE TITLE
Does libxla_extension.so provide definitions for all the declarations in include/?

### ISSUE THREAD

**Issue by joelberkeley** [elixir-nx/xla#12]
I'm new to C++ compilation, and wanted to check I've understood what this package provides. For every declaration in the header files in the include/ directory in the released packages, is there a corresponding definition in the libxla_extension.so shared library?

**Comment by seanmor5** [comment]
There should be: https://github.com/elixir-nx/xla/blob/main/extension/BUILD#L67

This line uses the dependencies specified and gets every header referenced for dependencies and nested dependencies. It's possible there might be some discrepancies though

**Comment by joelberkeley** [comment]
OK. I'm trying to use `double_conversion::Bignum` to check my setup works, and it's not finding the constructor or a number of attributes. Do you happen to know if there are definitions for that class?

**Comment by joelberkeley** [comment]
I'm able to call into util/utf.h, which suggests my setup is largely correct, and that either `Bignum` is missing or there is something to do with classes or namespaces that I've missed

**Comment by joelberkeley** [comment]
Fixed it. I was compiling it wrong. Thanks for your help
