### ISSUE TITLE
Release as a static library

### ISSUE THREAD

**Issue by joelberkeley** [elixir-nx/xla#20]
Is it possible to provide a static library release?

Atm I'm wrapping the API in `extern "C"` code and calling it from Idris. This means my Idris library requires two dynamic libs (XLA and the wrapper). This adds complexity, and it would be really nice to just have one.

**Comment by seanmor5** [comment]
Unfortunately we don't really have a use-case for it in our libraries upstream, so it's not something we can officially support. It should; however, be easy to fork this and modify the build rules in `extension/BUILD` to achieve this. I would recommend looking here: https://docs.bazel.build/versions/main/be/c-cpp.html

**Comment by joelberkeley** [comment]
OK, thanks. In that case, I'm wondering if I should use the bazel script or the elixir wrapping code
