### ISSUE TITLE
Out of memory while trying to allocate

### ISSUE THREAD

**Issue by krainboltgreene** [elixir-nx/xla#32]
Apologies if this is the wrong repository for this, but I tried to get into `iex` and received this error:

```
[info] Sum Total of in-use chunks: 3.96GiB
[info] total_region_allocated_bytes_: 4928097280 memory_limit_: 4928097484 available bytes: 204 curr_region_allocation_bytes_: 9856195072
[info] Stats: 
Limit:                      4928097484
InUse:                      4248542720
MaxInUse:                   4248542720
NumAllocs:                        1040
MaxAllocSize:                151781376
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

[warning] ****************************************************************************************************
[error] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 58982400 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:   56.25MiB
              constant allocation:         0B
        maybe_live_out allocation:   56.25MiB
     preallocated temp allocation:         0B
                 total allocation:  112.50MiB
              total fragmentation:         0B (0.00%)
Peak buffers:
        Buffer 1:
                Size: 56.25MiB
                Entry Parameter Subshape: f32[14745600]
                ==========================

        Buffer 2:
                Size: 56.25MiB
                XLA Label: copy
                Shape: f32[1280,1280,3,3]
                ==========================

        Buffer 3:
                Size: 8B
                XLA Label: tuple
                Shape: (f32[1280,1280,3,3])
                ==========================
```

Sadly it doesn't really give me much to go on, but I think this is inside xla?

**Comment by seanmor5** [comment]
Can you try setting `memory_fraction: 0.5` when initializing your EXLA client?

**Comment by krainboltgreene** [comment]
I saw that and assumed I was out of luck since it starts at 0.9 (thinking I had to give it more power). When setting it to `0.5` I get no fancy output above, but it did change the value and still crashed:

```
[warning] *************************************************************************************************___
[notice] Application genie exited: exited in: Genie.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Out of memory while trying to allocate 117964800 bytes.
```

**Comment by seanmor5** [comment]
@josevalim we don't try to place anything on the device just on startup right?

**Comment by josevalim** [comment]
I don't think we do. @krainboltgreene do you have more stacktrace entries?

**Comment by krainboltgreene** [comment]
Here's the complete output from both settings: https://gist.github.com/krainboltgreene/fd4ff0a0f2da99b160c85a5bc2dcfdb2

**Comment by josevalim** [comment]
@seanmor5 so the error is happening when trying to load the model. Is this Stable Diffusion @krainboltgreene? I don't think the parameter for it are that large, right?

**Comment by krainboltgreene** [comment]
Would it help for me to post my `application.ex`?

**Comment by josevalim** [comment]
No need for now, we will see how things evolve. :)

**Comment by josevalim** [comment]
Ok, so this is expected because the SD model takes 4GB. Right now we load all data upfront to the GPU and we will perhaps need to figure out a way of loading the data to memory/disk first. But this is a Bumblebee concern.

**Comment by josevalim** [comment]
Please follow this issue meanwhile @krainboltgreene: https://github.com/elixir-nx/bumblebee/issues/101
