### ISSUE TITLE
Any chance of a non-Cuda, non-Darwin, AARCH64 XLA build?

### ISSUE THREAD

**Issue by vegabook** [elixir-nx/xla#36]
I'm having real trouble compiling XLA using the `XLA_BUILD=true` directive because I'm running Ubuntu 22.04 on an Arm64 device (Raspberry Pi 4b 4GB). 
It wants Bazel which has to be compiled, but which fails after a while on Arm Ubuntu for some reason I cannot fathom. 
Also I suspect, as like when I tried with a Jetson Nano, that Bazel + XLA will compile Tensorflow and perhaps Jax which will be impossibly slow and crash frequently due to memory issues. 

Given that I think that quite a few people might use Arm64 boards for edge inference, would you consider a prebuilt XLA image that does not require Cuda or a Mac?  https://github.com/elixir-nx/xla/releases/tag/v0.4.3

**Comment by seanmor5** [comment]
In the past we had somebody build these locally and upload so they could be used pre-built. I'm sure we can look into a way to provide pre-built versions of these binaries

**Comment by polvalente** [comment]
I can look into this @seanmor5!
I've been meaning to try out Nx on the RPi, so this sounds like the perfect excuse

**Comment by josevalim** [comment]
IIRC we had issues on aarm64 for Docker, so you may need an actual aarm64 machine (which may take a while). @zacky1972 was the one helping us in the past. :)

**Comment by Benjamin-Philip** [comment]
> I can look into this @seanmor5!
> I've been meaning to try out Nx on the RPi, so this sounds like the perfect excuse

Off topic, but I tried Nx on a Pi 400 sometime in late 2021 or early 2022 and compiling Nx even without EXLA or Torchx took forever.

To top that, BinaryBackend was extra slow, so any practical applications were out of question.

Have fun!

**Comment by Benjamin-Philip** [comment]
> In the past we had somebody build these locally and upload so they could be used pre-built. I'm sure we can look into a way to provide pre-built versions of these binaries

Forgive me if I'm missing something, but can't we just cross compile xla for aarch64 from an x86 64 machine?

**Comment by polvalente** [comment]
> Forgive me if I'm missing something, but can't we just cross compile xla for aarch64 from an x86 64 machine?

We don't have much control over the bazel build for XLA. It might be worth a shot playing with different CC/CXX/CFLAGS/LFLAGS configurations, though.

**Comment by Benjamin-Philip** [comment]
> > Forgive me if I'm missing something, but can't we just cross compile xla for aarch64 from an x86 64 machine?
> 
> We don't have much control over the bazel build for XLA. It might be worth a shot playing with different CC/CXX/CFLAGS/LFLAGS configurations, though.

I think we just need to change the Bazel platform in the Bazel flags as shown in the [docs](https://bazel.build/concepts/platforms). Surely XLA's Bazel config has support for multiple platforms.

**Comment by josevalim** [comment]
> Off topic, but I tried Nx on a Pi 400 sometime in late 2021 or early 2022 and compiling Nx even without EXLA or Torchx took forever.

that’s why Nerves compiles everything on your machine and then you transfer it :)

**Comment by polvalente** [comment]
This might be relevant: https://github.com/xifengcun/tensorflow-aarch64-crossbuild

**Comment by Benjamin-Philip** [comment]
This too: https://www.tensorflow.org/lite/guide/build_arm#cross-compilation_for_arm_with_bazel

However that link is only speaks for TF lite.

**Comment by polvalente** [comment]
I successfully built XLA locally on the RaspberryPi 4!
Not exactly the ideal solution, but at least we can publish the archive for now.

I think we should still investigate this cross-compilation strategy further.

**Comment by jonatanklosko** [comment]
@vegabook we will now cross-compile on CI. I also added a binary to the v0.4.3 release :)

**Comment by vegabook** [comment]
Awesome 

> I successfully built XLA locally on the RaspberryPi 4! Not exactly the ideal solution, but at least we can publish the archive for now.
> 
> I think we should still investigate this cross-compilation strategy further.

Incredible. Thank you. Can you let me know the steps to do it?

**Comment by polvalente** [comment]
@vegabook you don't need to build locally anymore as per #37
Now it should just download normally.

However, it's not that hard. You need to get [Bazel 5.3.0 for arm64](https://github.com/bazelbuild/bazel/releases/tag/5.3.0), put it in your path (i.e. `/usr/bin/bazel`) and install everything else that's installed on the Dockefile (I used the [Cuda](https://github.com/elixir-nx/xla/blob/main/.github/builds/Dockerfile.cuda) one as a reference).

I didn't have any problems aside from a missing `chmod +x` on the Bazel executable and from a Elixir/Erlang version conflict, but I installed those through `asdf` on the Pi and it worked fine.

Takes a few hours though.

With the built binary in hand, you need to set `XLA_BUILD=true` and the `XLA_CACHE_DIR` to the same one to which you built the binary.

**Comment by vegabook** [comment]
Just for completeness, working great. Looks like roughly 4x slower than optimized Numpy but that's perfectly acceptable and I think it'll probably beat Python handsomely as matrices get bigger and/or more complex compute graphs and/or GPU gets involved. 

So fantastic stuff. 

```
tatbrowne@rpi2204 ~/code/elixir/nxtest iex -S mix
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

warning: variable "u" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/svdtest.ex:20

warning: variable "vt" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/svdtest.ex:20

Interactive Elixir (1.15.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Svdtest.run_test(Svdtest.finurl)

23:00:12.573 [info] TfrtCpuClient created.
#Nx.Tensor<
  f32[16]
  EXLA.Backend<host:0, 0.1788470111.1459486728.165786>
  [6.730020046234131, 4.988578796386719, 2.531365156173706, 0.6920415163040161, 0.42454540729522705, 0.18819230794906616, 0.1419195681810379, 0.07709477096796036, 0.06985979527235031, 0.05112181976437569, 0.0388726107776165, 0.02799767255783081, 0.016022056341171265, 0.012146146036684513, 0.008691186085343361, 0.001557462033815682]
>
Time taken: 3.922988 seconds
:ok
iex(2)> Svdtest.run_test(Svdtest.finurl)
#Nx.Tensor<
  f32[16]
  EXLA.Backend<host:0, 0.1788470111.1459486728.165789>
  [6.730020046234131, 4.988578796386719, 2.531365156173706, 0.6920415163040161, 0.42454540729522705, 0.18819230794906616, 0.1419195681810379, 0.07709477096796036, 0.06985979527235031, 0.05112181976437569, 0.0388726107776165, 0.02799767255783081, 0.016022056341171265, 0.012146146036684513, 0.008691186085343361, 0.001557462033815682]
>
Time taken: 0.00413 seconds
:ok
iex(3)> Svdtest.run_test(Svdtest.finurl)
#Nx.Tensor<
  f32[16]
  EXLA.Backend<host:0, 0.1788470111.1459486728.165792>
  [6.730020046234131, 4.988578796386719, 2.531365156173706, 0.6920415163040161, 0.42454540729522705, 0.18819230794906616, 0.1419195681810379, 0.07709477096796036, 0.06985979527235031, 0.05112181976437569, 0.0388726107776165, 0.02799767255783081, 0.016022056341171265, 0.012146146036684513, 0.008691186085343361, 0.001557462033815682]
>
Time taken: 0.00349 seconds
:ok
iex(4)> 
```
you can find the code [here](https://github.com/vegabook/nxtest).

**Comment by Benjamin-Philip** [comment]
I would like to see if the precompiled binary is equally performant as a natively compiled binary on a regular arm64 machine.

The docs mention that the `--config=elinux-aarch64` being experimental and specialised for the RPi 4.

**Comment by jonatanklosko** [comment]
@Benjamin-Philip fwiw the binary actually works for me on ARM Mac inside Docker.

**Comment by Benjamin-Philip** [comment]
Cool. Maybe I'll some benchmarks sometime later.

**Comment by vegabook** [comment]
So @Benjamin-Philip my toy example worked at similar speed in Nx and Numpy on a 2015-era (no AVX512) Xeon box. You can see it on the Elixir Forum [here](https://elixirforum.com/t/nx-appears-to-be-extremely-slow-for-singular-value-decomposition-like-50k-times-slower-than-numpy/52882/6?u=vegabook).
