### ISSUE TITLE
Fail to download pre-build dll for Intel Mac

### ISSUE THREAD

**Issue by zacky1972** [elixir-nx/xla#52]
Hi,

I've built CI using GitHub Actions and EXLA.

It succeeded when 0.5 but failed when 0.6. The log shows downloading was failed.

XLA still supports Intel Mac? Will binary for it be available?

**Comment by josevalim** [comment]
Download worked fine for me on both Intel and Arm Macs. What are your logs? Could it be something related to the internet connection?

**Comment by zacky1972** [comment]
Oh, really?

I'm testing it again.

**Comment by jonatanklosko** [comment]
This is the same as #43. GitHub Actions macOS runners have fixed IPs, so calls to GitHub API may fall under rate limiting. You can try authorizing the requests by using the CI token:

```yaml
env:
  XLA_HTTP_HEADERS: "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
```

**Comment by zacky1972** [comment]
@jonatanklosko Thanks! It works well!
