### ISSUE TITLE
XLA_TARGET for Apple Metal Silicon?

### ISSUE THREAD

**Issue by shaqq** [elixir-nx/xla#74]
Apologies for the n00b question

If I want BumbleBee/Axon/EXLA to use GPUs on Apple M1 Silicon via Metal, what should I set the `XLA_TARGET` to?

**Comment by josevalim** [comment]
XLA has no official support afaik. Apple release some plugin for old versions but afaik that is already outdated.

**Comment by shaqq** [comment]
I see - I think https://github.com/elixir-nx/xla/pull/51 is the reference issue, and maybe https://github.com/google/jax/issues/8074. 

I can send up a PR to the README here to clarify this. I'm sure others are looking to use Bumblebee on their Macs and want to know if it works on Apple Metal.

**Comment by joelberkeley** [comment]
Any progress with this? I'm trying to build the PJRT plugin myself but don't know where to start. It's far more opaque than building for aarch64 CPUs.

**Comment by polvalente** [comment]
We've released elixir-nx/emlx for Metal support!

There's still some work needed for compiler acceleration, but I was already able to see some improvements on workflows that don't make use of the EXLA compiler, just the backend.

**Comment by josevalim** [comment]
The plugins are out of scope for this repository but the good news is that you should be able to just import existing precompiled ones. Here is a PR where we add support for Metal plugins in Nx: https://github.com/elixir-nx/nx/pull/1504 - but it wasn't merged yet because several operations are missing on Apple's plugins and unfortunately the plugin is closed source.

**Comment by joelberkeley** [comment]
OK so the jax metal plugin packaged in the python wheel isn't python-specific (as many jax things are, I think)? And it can be used as a normal PjRt plugin?

**Comment by jonatanklosko** [comment]
@joelberkeley correct, it's just a PjRt plugin!

**Comment by joelberkeley** [comment]
Do you know if it's an XLA plugin? The website says

> The Metal plugin uses the OpenXLA compiler

but OpenXLA is an ecosystem not a compiler.

**Comment by jonatanklosko** [comment]
I'm not sure what you mean by XLA plugin :D There are many parts, so I may be missing the right wording, but the Jax Metal provides a PjRt plugin API implementation, in the sense that you load a dynamic library via `pjrt::LoadPjrtPlugin`.

**Comment by joelberkeley** [comment]
> I'm not sure what you mean by XLA plugin

A PjRt plugin that uses the XLA compiler.

> in the sense that you load a dynamic library via `pjrt::LoadPjrtPlugin`

ah, so this plugin doesn't have a C API for use with the PjRt C API?

**Comment by joelberkeley** [comment]
I need to read that function. I've not seen it before
