### ISSUE TITLE
XLA Slow operation alarms: "The operation took ..."

### ISSUE THREAD

**Issue by Szetty** [elixir-nx/xla#76]
Hello, we are having logs like this in our Elixir project:

```
The operation took 2m32.409760523s

********************************
[Compiling module _Function_4.57852891_4_in_Axon.Loop.build_batch_fn_2_.32279] Very slow compile? If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
********************************
```

As they are logged as errors they appear in our production logging system. I have tracked down and found that they are coming from: [XLA](https://github.com/openxla/xla/blob/0388888727a0e25e07f01c92cd63ec5f907c83fc/xla/service/slow_operation_alarm.cc#L133D).

Do you know if there is a way to disable them ?

**Comment by josevalim** [comment]
There is no way to cancel it upstream, I believe. You would have to ask on the official repo, in this repo we only build the executable.

**Comment by seanmor5** [comment]
This happens from really expensive compilations. What specifically are you doing? Maybe we can find a way to simplify the executable you're trying to compile

**Comment by seanmor5** [comment]
An example would be if you're training an RNN, and unrolling the entire sequence then it will result in this error

**Comment by jonatanklosko** [comment]
I don't think there's anything actionable on our side, so I'm going to close this.
