### ISSUE TITLE
Could not find v0.6.0 release under https://github.com/elixir-nx/xla/releases

### ISSUE THREAD

**Issue by mickel8** [elixir-nx/xla#91]
Hi,
time to time, I am getting the following error when running xla on the CI:

```
==> exla
** (RuntimeError) could not find v0.6.0 release under https://github.com/elixir-nx/xla/releases
    (xla 0.6.0) lib/xla.ex:195: XLA.download_matching!/1
    (xla 0.6.0) lib/xla.ex:33: XLA.archive_path!/0
    /Users/runner/work/xav/xav/deps/exla/mix.exs:113: EXLA.MixProject.extract_xla/1
    (mix 1.17.2) lib/mix/task.ex:574: Mix.Task.run_alias/6
    (mix 1.17.2) lib/mix/tasks/compile.all.ex:108: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.17.2) lib/mix/tasks/compile.all.ex:88: Mix.Tasks.Compile.All.compile/4
    (mix 1.17.2) lib/mix/tasks/compile.all.ex:62: Mix.Tasks.Compile.All.run/1
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
```

Sometimes it works, sometimes it does not.

CI runs on GitHub workflows, macos 14 :eyes:

**Comment by josevalim** [comment]
I think this is GitHub rate limiting your CI. You should be able to fix this by adding a token. We should improve the error message here.

**Comment by josevalim** [comment]
I am almost sure it is GitHub rate limiting. But the only way to address this is by adding a GitHub token to the HTTP headers. @jonatanklosko I am almost sure we did this for another project somewhat recently. Can you remember which one was it?

**Comment by mickel8** [comment]
No worries! The hint to try to use a token is good enough. I will try to test it tomorrow or on Monday!

**Comment by jonatanklosko** [comment]
See https://github.com/elixir-nx/xla/issues/52#issuecomment-1686162988 :D 

May be worth a more detailed error, yeah!

**Comment by jonatanklosko** [comment]
@josevalim perfect, thanks!
