### ISSUE TITLE
Missing tools directory

### ISSUE THREAD

**Issue by peastman** [elixir-nx/xla#97]
I tried to use your precompiled libraries to build the minimal example at https://github.com/google/jax/blob/234be736c4cdd8da4197078278d35a6a1cde3767/examples/jax_cpp/main.cc.  It fails because they don't include the `xla/tools` directory, which contains `LoadModuleFromFile()`.

Would you consider adding it?  That would make these libraries much more generally useful, not just for Elixer (though I understand that's the main purpose of them).

**Comment by josevalim** [comment]
Thank you but we don’t have plans at the moment. It is very easy to inflate the binary size by adding deps we don’t need, which is why we plan to keep them minimal. :)

**Comment by peastman** [comment]
Oh well, I understand.  I figured it was worth asking!
